[package]
name = "gloam-engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
macroquad = "0.3"
wasm-bindgen = "0.2.84"
js-sys = "0.3.59"

image = "0.24.6"
data-url = "0.2.0"

[dependencies.web-sys]
version = "0.3.61"

features = [
    'console',
#    'Document',
#    'Element',
#    'HtmlCanvasElement',
#    'HtmlImageElement',
#    'Performance',
#    'WebGlFramebuffer',
#    'WebGl2RenderingContext',
#    'WebGlUniformLocation',
#    'WebGlBuffer',
#    'WebGlProgram',
#    'WebGlShader',
#    'WebGlVertexArrayObject',
#    'WebGlTexture',
#    'Window',
]